import io
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
import torch

print("=" * 78)
print("第 0 步: 一维, 没有逗号 —— 只有'要哪些'")
print("=" * 78)
v = torch.tensor([10, 11, 12, 13, 14])
print(f"  v = {v.tolist()}   (就一条线, 5 个元素)")
print()
print(f"  v[2]     = {v[2].item()}          <- 要第 2 个")
print(f"  v[1:4]   = {v[1:4].tolist()}      <- 要第 1,2,3 个(不含 4)")
print(f"  v[:]     = {v[:].tolist()}   <- 全要")
print()
print("  这就是全部: 方括号里写'我要这条线上的哪几个'")

print("\n" + "=" * 78)
print("第 1 步: 二维 = 表格, 有行有列 -> 用逗号分开")
print("=" * 78)
m = torch.arange(12).reshape(3, 4)
print("  m = (3 行 4 列)")
for row in m.tolist():
    print(f"      {row}")
print()
print("  现在有 TWO 个方向, 所以方括号里写 TWO 段, 用逗号隔开:")
print("     m[ 第几行 , 第几列 ]")
print("        └─第1段─┘ └─第2段─┘")
print()
print(f"  m[1, 2]   = {m[1, 2].item()}      <- 第1行 第2列")
print(f"  m[0]      = {m[0].tolist()}   <- 只写第1段: 第0行(整行)")
print(f"  m[:, 2]   = {m[:, 2].tolist()}      <- 第2段给2: 每一行的第2列")
print(f"  m[1, :]   = {m[1, :].tolist()}   <- 第1段给1: 第1行全部")
print(f"  m[:, :]   = 整个表格")
print()
print("  关键: 逗号的个数 = 这个张量有几个方向(维度)")

print("\n" + "=" * 78)
print("第 2 步: 每一段写什么 —— 只有 3 种情况")
print("=" * 78)
print("  用第 1 段(行方向)举例, m 有 3 行:")
print()
print(f"    写一个数字 1    -> m[1]    = {m[1].tolist()}      '只要第 1 行'(行没了, 剩下列)")
print(f"    写 :           -> m[:]    3 行全要")
print(f"    写 0:2         -> m[0:2]  第 0,1 行")
print()
print("  所以每一段的含义就是: '在这个方向上, 我要哪几个'")
print("    数字 = 只要那一个(这个方向就消失了)")
print("    :    = 全要(方向保留)")
print("    a:b  = 要一段(方向保留)")

print("\n" + "=" * 78)
print("第 3 步: 三维 = 一摞表格 -> 逗号变两个")
print("=" * 78)
x = torch.arange(24).reshape(2, 3, 4)
print(f"  x.shape = {tuple(x.shape)}   = 2 张表, 每张 3 行 4 列")
print()
print("     x[ 第几张表 , 第几行 , 第几列 ]")
print("        └─第1段──┘ └第2段┘ └第3段┘")
print()
print(f"  x[1, 2, 3] = {x[1, 2, 3].item()}     <- 第1张表 第2行 第3列")
print(f"  x[0]       -> shape {tuple(x[0].shape)}    <- 只要第1段: 第0张表")
print(f"  x[:, 1]    -> shape {tuple(x[:, 1].shape)}    <- 每张表的第1行")
print(f"  x[..., 3]  -> shape {tuple(x[..., 3].shape)}    <- 见下一步")

print("\n" + "=" * 78)
print("第 4 步: ... 就是'我懒得写的那几段 :'")
print("=" * 78)
print("  假设我只关心'最后那一列', 前面几段我都要:")
print()
print("    笨写法: x[:, :, 3]        <- 老老实实写 3 段")
print("    懒写法: x[...,  3]        <- ... 替我把前 2 段补上")
print()
print(f"  x[:, :, 3]  shape = {tuple(x[:, :, 3].shape)}")
print(f"  x[..., 3]   shape = {tuple(x[..., 3].shape)}")
print(f"  一样 ? {torch.equal(x[:, :, 3], x[..., 3])}")
print()
print("  ... 的真实身份: 编译器把它换成足够多的 :")
print("     x[..., 3]  -->  x[:, :, 3]        (3维, 所以要补 2 个 :)")
print()
print("  好处: 张量从 3 维变 4 维时, 不用改代码")
print("     q[..., 3]")
print("       3维时 -> q[:, :, 3]")
print("       4维时 -> q[:, :, :, 3]      <- 代码一个字没改")

print("\n" + "=" * 78)
print("第 5 步: 现在回头读 rotate_half, 一句句念出来")
print("=" * 78)
code = "x[..., x.shape[-1] // 2 :]"
print(f"  {code}")
print()
print("  念法: '所有前面的维度都要(...,), 最后一维从 一半 到 末尾'")
print("     ...                  -> 前面所有维度: 全要")
print("     x.shape[-1] // 2     -> 最后一维长度的一半(比如 8//2 = 4)")
print("     4 :                  -> 从下标 4 到末尾")
print()
h = 4
xq = torch.arange(8.0)
print(f"  具体例子: 最后一维是 [0,1,2,3,4,5,6,7], h = {h}")
print(f"    x[..., {h}:]   = {xq[..., h:].tolist()}   <- 后半")
print(f"    x[..., :{h}]   = {xq[..., :h].tolist()}   <- 前半")
print()
print("  所以 rotate_half = '后半取负 + 前半' 拼起来:")
print(f"    {(-xq[..., h:]).tolist()} + {xq[..., :h].tolist()} = {torch.cat((-xq[..., h:], xq[..., :h]), dim=-1).tolist()}")

print("\n" + "=" * 78)
print("一张速查表(记住这一张就够)")
print("=" * 78)
print("  方括号里的结构:")
print()
print("    x[  段1  ,  段2  ,  段3  ]")
print("         ↓       ↓       ↓")
print("       管维度0  管维度1  管维度2")
print()
print("  每一段可以写:")
print("    3        只要第 3 个     (该维消失)")
print("    :        全要            (该维保留)")
print("    1:4      要 1,2,3        (该维保留)")
print("    ...      替我把剩下的段都写成 :")
print()
print("  段数 < 维度数 时, 后面的维度自动全要(隐式 :)")
print(f"    实测: x[0] 等于 x[0, :, :] ? {torch.equal(x[0], x[0, :, :])}")
