import io
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
import torch

x = torch.arange(6).reshape(1, 2, 3)
print(f"x.shape = {tuple(x.shape)}   元素 {x.numel()} 个")
print(f"x =\n{x}\n")

print("=" * 78)
print("刺 1(最关键): :1 里的数字是'长度', 不是'下标/坐标'")
print("=" * 78)
print("  你写的 :1, :2 恰好和原 shape 的 2、3 数字接近, 容易误以为'在挑原坐标'")
print("  实际上 :n 的含义是'取前 n 个', n 是'要留几个'")
print()
for n in [0, 1, 2, 3, 5]:
    r = x[:, :n] if n <= 2 else None
    if r is not None:
        print(f"    x[:, :{n}] -> shape {tuple(r.shape)}   (留了 {n} 个)")
    else:
        print(f"    x[:, :{n}] -> shape {tuple(x[:, :n].shape)}   (留了 {min(n,2)} 个, 超出的部分是空的)")
print()
print("  用 3 维自己验证:")
print(f"    x[:, :, :2]  -> shape {tuple(x[:, :, :2].shape)}   最后一维留 2 个")
print(f"    x[:, :, :1]  -> shape {tuple(x[:, :, :1].shape)}   最后一维留 1 个")
print(f"    x[:, :, :0]  -> shape {tuple(x[:, :, :0].shape)}   留 0 个(合法, 空)")
print()
print("  所以 :1 的 1 和原 shape 里的 2、3 没有任何关系")
print("  '切成 [1,1,2]' 是因为你恰好要留 1 个和 2 个, 而不是因为原 shape 是 2 和 3")

print("\n" + "=" * 78)
print("刺 2: 切片只能'截断', 不能'任意切形状'")
print("=" * 78)
print("  切片每维长度只能 <= 原长度, 且保留连续的一段")
print("  不能: 变长、非连续、重排")
print()
print(f"  x.shape = {tuple(x.shape)}  各维长度 = {tuple(x.shape)}")
print("  可达的 shape: 第一维只能 1; 第二维 0~2; 第三维 0~3")
print(f"    例: x[:, 1:, ::2] -> shape {tuple(x[:, 1:, ::2].shape)}   (用步长可以挑非连续)")
print(f"    例: x[:, :, ::-1] -> torch 不支持负步长(前面已验证)")
print()
print("  想得到'非截断'的形状, 必须用 reshape / permute / index_select 等")
print(f"    例: x.reshape(2,3) -> shape {tuple(x.reshape(2,3).shape)}   <- 这已经不是切片了")

print("\n" + "=" * 78)
print("刺 3: '前/后'的说法要分清'留'还是'砍'")
print("=" * 78)
print(f"  x2 = {[0,1,2,3,4,5]}")
v = torch.arange(6)
print(f"    v[:2] = {v[:2].tolist()}     <- 留【前】2 个")
print(f"    v[2:] = {v[2:].tolist()}     <- 砍【前】2 个 = 留【后】4 个")
print()
print("  你说'保留的是什么, 是前还是后? 前'—— 对, 但要看句子的主语:")
print("    :2   -> 留前 2 个        (砍后面)      : 在右 -> 砍右")
print("    2:   -> 砍前 2 个        (留后面)      : 在左 -> 砍左")
print("  两种说法会绕, 建议统一成: ': 左边的数字砍左, 右边的数字砍右'")

print("\n" + "=" * 78)
print("刺 4: '全保留几乎用不上' —— 不完全对")
print("=" * 78)
print("  x[...] 单独写确实少见, 但它在 3 个场景有用:")
print()
print("  (1) 统一写法: 代码里 q 的维度数是可变的")
for shape in [(3, 4), (2, 3, 4), (2, 4, 6, 8)]:
    t = torch.zeros(shape)
    print(f"      t.shape {str(shape):<18} -> t[..., 0].shape {tuple(t[..., 0].shape)}")
print("      同一个表达式适配 2/3/4 维")
print()
print("  (2) 明确表示'这里要一个切片'")
print("      x[:, None]  和  x[..., None] 语义不同")
print(f"      x[:, None].shape    = {tuple(x[:, None].shape)}")
print(f"      x[..., None].shape  = {tuple(x[..., None].shape)}")
print()
print("  (3) 返回视图(不是拷贝) —— 这在内存和梯度上是重要区别")
a = torch.arange(6)
b = a[...]
print(f"      b = a[...]  b 和 a 共享内存 ? {b.data_ptr() == a.data_ptr()}")
print("      (x[...] 返回视图, 不复制数据)")

print("\n" + "=" * 78)
print("刺 5: 术语 —— 精确说'改变各维长度', 不是'切 shape'")
print("=" * 78)
print("  shape 是'各维长度的元组', 切片改的是长度, shape 跟着变")
print(f"    x.shape          = {tuple(x.shape)}")
print(f"    x[:, :1, :2].shape = {tuple(x[:, :1, :2].shape)}")
print("  说'切成 [1,1,2]'口语上没问题, 书面建议说'各维长度变成 (1,1,2)'")

print("\n" + "=" * 78)
print("核对你的两个写法(都对)")
print("=" * 78)
r1 = x[:, :1, :2]
r2 = x[..., :1, :2]
print(f"  x[:, :1, :2]  -> shape {tuple(r1.shape)}")
print(f"  x[..., :1, :2] -> shape {tuple(r2.shape)}")
print(f"  两者相同 ? {torch.equal(r1, r2)}")
print()
print(f"  x[..., :1, :2] 里 ... 展开成 {x.dim() - 2} 个冒号 -> {tuple(r1.shape)}")

print("\n" + "=" * 78)
print("验证一下'砍'的写法(你的最后一问)")
print("=" * 78)
print(f"  x.shape = {tuple(x.shape)}")
print(f"  x[:, 1:, :]   -> shape {tuple(x[:, 1:, :].shape)}   砍掉第 1 维的前 1 个")
print(f"  x[:, :, 1:]   -> shape {tuple(x[:, :, 1:].shape)}   砍掉第 2 维的前 1 个")
print(f"  x[:, 1:, 1:]  -> shape {tuple(x[:, 1:, 1:].shape)}   都砍")
print()
print("  注意: '砍'和'留'是同一件事的两种说法")
print("    x[:, :, 1:]  留后 2 个  ==  砍前 1 个")
print(f"    验证: x[:, :, 1:] 和 x[:, :, -2:] 一样 ? {torch.equal(x[:, :, 1:], x[:, :, -2:])}")
