import io
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
import torch

x = torch.arange(2 * 3 * 8).reshape(2, 3, 8)
h = x.shape[-1] // 2
print(f"x.shape = {tuple(x.shape)}   最后一维长度 = {x.shape[-1]},  h = {h}\n")

print("=" * 78)
print("一句话翻译")
print("=" * 78)
print("  x[..., x.shape[-1] // 2 :]")
print("      ↓           ↓        ↓")
print("   前面维度      一半      从一半到末尾")
print("   全要         = 4")
print()
print("  读作: '前面所有维度全要, 最后一维从下标 4 取到末尾'")
print("  结果: 取最后一维的'后半'")

print("\n" + "=" * 78)
print("实测: 最后一维到底变成了什么")
print("=" * 78)
print(f"  x[0,0]        = {x[0,0].tolist()}      (最后一维 8 个)")
print(f"  x[..., {h}:][0,0] = {x[..., h:][0,0].tolist()}      (最后一维剩 {len(x[..., h:][0,0])} 个)")
print()
print(f"  x[..., {h}:].shape = {tuple(x[..., h:].shape)}")
print()
print("  对比:")
print(f"    x[..., :{h}]  -> 后半取完了? 不, 这是'前半' -> shape {tuple(x[..., :h].shape)}")
print(f"    x[..., {h}:]  -> 这是'后半'              -> shape {tuple(x[..., h:].shape)}")

print("\n" + "=" * 78)
print("纠正 1: 是'后半', 不是'砍掉一半'")
print("=" * 78)
print("  最后一位的下标范围是 0~7, 共 8 个")
print(f"    x[..., {h}:]  取下标 {h},{h+1},...,7     -> 4 个(后半)")
print(f"    x[..., :{h}]  取下标 0,1,...,{h-1}       -> 4 个(前半)")
print()
print("  切片规则 [起点:终点]: 含起点不含终点")
print(f"    {h}:     起点={h}, 终点省略=到末尾")
print(f"    :{h}     起点省略=0, 终点={h}(不含)")
print()
print("  '砍掉一半'听起来像'把后半删了', 实际是'只取后半'")
print("  两者结果规模一样, 但取的是不同的一半:")
print(f"    取后半: {x[0,0][h:].tolist()}")
print(f"    取前半: {x[0,0][:h].tolist()}")

print("\n" + "=" * 78)
print("纠正 2: 维度不会消失, 只是变短")
print("=" * 78)
print(f"  x.shape        = {tuple(x.shape)}   维度数 {x.dim()}")
print(f"  x[..., {h}:].shape = {tuple(x[..., h:].shape)}   维度数 {x[..., h:].dim()}   <- 还是 3 维!")
print()
print("  对比'维度真的消失'的情况:")
print(f"    x[..., 0].shape  = {tuple(x[..., 0].shape)}   维度数 {x[..., 0].dim()}   <- 整数索引, 砍掉一维")
print(f"    x[..., 0:1].shape= {tuple(x[..., 0:1].shape)}   维度数 {x[..., 0:1].dim()}   <- 切片, 保留维度")
print()
print("  规律:")
print("    整数 3   -> 该维消失(降维)")
print("    切片 a:b -> 该维保留(只变短)")

print("\n" + "=" * 78)
print("完整拆解这个表达式")
print("=" * 78)
expr = "x[..., x.shape[-1] // 2 :]"
print(f"  {expr}")
print()
print("  第 1 部分: ...")
print(f"     展开成 {x.dim() - 1} 个冒号(因为右边还有 1 段)")
print(f"     等价于 x[:, :, ...]")
print("     作用: 前面所有维度全要")
print()
print("  第 2 部分: x.shape[-1] // 2")
print(f"     x.shape[-1] = {x.shape[-1]}     取最后一维长度")
print(f"     // 2        = {h}       整除, 得一半")
print("     作用: 算出切分点")
print()
print("  第 3 部分: :")
print(f"     从下标 {h} 到最后")
print("     作用: 取后半段")
print()
print("  合起来 = '前面全要, 最后一维取后半'")
print()
print(f"  等价写法对比:")
for e, fn in [("x[..., 4:]", lambda t: t[..., 4:]),
              ("x[:, :, 4:]", lambda t: t[:, :, 4:]),
              ("x[:, :, x.shape[-1]//2:]", lambda t: t[:, :, t.shape[-1] // 2:])]:
    r = fn(x)
    print(f"    {e:<28} -> shape {tuple(r.shape)}")

print("\n" + "=" * 78)
print("在 rotate_half 里的角色")
print("=" * 78)
print("  def rotate_half(x):")
print("      return torch.cat(")
print("          (-x[..., x.shape[-1]//2 :],   <- 后半, 取负")
print("            x[..., : x.shape[-1]//2]),  <- 前半")
print("          dim=-1)")
print()
vec = torch.arange(8.0)
print(f"  例: x = {vec.tolist()}   (最后一维 8 个)")
print(f"      后半 x[..., 4:]  = {vec[4:].tolist()}")
print(f"      前半 x[..., :4]  = {vec[:4].tolist()}")
print(f"      后半取负         = {(-vec[4:]).tolist()}")
print(f"      拼接结果         = {torch.cat((-vec[4:], vec[:4])).tolist()}")
print()
print("  所以整句的意思是: 把'后半取负'放前面, '前半'放后面 —— 前后对调!")
print(f"  原顺序: {vec.tolist()}")
print(f"  新顺序: {torch.cat((-vec[4:], vec[:4])).tolist()}   <- 前4个和后4个换了位置")
