import io
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
import torch

x = torch.arange(24).reshape(2, 3, 4)
print(f"x.shape = {tuple(x.shape)}   维度数 n = 3\n")

print("=" * 78)
print("你的理解逐条核对")
print("=" * 78)
print("  ① : 是保留       -> 对, :  保留这一维(维度数不变)")
print("  ② ... 是 n 个冒号 -> 对, 展开成 n 个 :")
print()

print("=" * 78)
print("核对 ①: : 确实'保留维度'")
print("=" * 78)
print(f"  {'写法':<18}{'结果 shape':<16}{'维度数变化'}")
print("  " + "-" * 54)
for expr, fn in [("x[:, :, :]", lambda t: t[:, :, :]),
                 ("x[:, 1, :]", lambda t: t[:, 1, :]),
                 ("x[1, 1, 1]", lambda t: t[1, 1, 1])]:
    r = fn(x)
    print(f"  {expr:<18}{str(tuple(r.shape)):<16}{x.dim()} -> {r.dim()}")
print()
print("  :  -> 维度数不变(保留)")
print("  数字 -> 维度数减少(该维消失)")

print("\n" + "=" * 78)
print("核对 ②: ... 展开成冒号, 每个冒号也各自保留一维")
print("=" * 78)
print("  x[..., 0]  展开成  x[:, :, 0]")
print("                    └─┬─┘  └┬┘")
print("                  ...补的2个  你写的")
print()
print("  这 2 个冒号各自作用在一个维度上:")
print("    第 1 个冒号  -> 第 0 维(长度 2)保留")
print("    第 2 个冒号  -> 第 1 维(长度 3)保留")
print("    你写的 0     -> 第 2 维(长度 4)取第 0 个, 该维消失")
print()
r = x[..., 0]
print(f"  实测: x[..., 0] shape = {tuple(r.shape)}")
print(f"        (2, 3, 4) 里去掉最后一维 -> (2, 3)   ✅ 前两维被冒号保留")

print("\n" + "=" * 78)
print("一张表说清三种东西的区别")
print("=" * 78)
print(f"  {'写法':<12}{'占几段':<10}{'作用范围':<14}{'效果'}")
print("  " + "-" * 62)
print(f"  {':':<12}{'1 段':<10}{'1 个维度':<14}保留这一维(维度数不变)")
print(f"  {'3':<12}{'1 段':<10}{'1 个维度':<14}取第 3 个(该维消失)")
print(f"  {'1:4':<12}{'1 段':<10}{'1 个维度':<14}取一段(维度保留)")
print(f"  {'...':<12}{'n-k 段':<10}{'若干个维度':<14}展开成若干个 : , 逐个保留")
print()
print("  关键: ... 不是'一种新的保留方式', 它只是'若干个 : 的简写'")
print("        所以 ... 的每一个展开出来的 : 都遵循' : 保留'这条规则")

print("\n" + "=" * 78)
print("验证: x[...] 就等于 x[:, :, :]")
print("=" * 78)
print(f"  x[...]       shape = {tuple(x[...].shape)}")
print(f"  x[:, :, :]   shape = {tuple(x[:, :, :].shape)}")
print(f"  内容相同 ? {torch.equal(x[...], x[:, :, :])}")
print("  -> ... 自己单独用时, 展开成 3 个冒号, 把 3 维全保留")

print("\n" + "=" * 78)
print("顺着这个理解读 rotate_half")
print("=" * 78)
print("  x[..., :h]")
print("     ...   -> 补 n-1 个冒号(前面所有维度保留)")
print("     :h    -> 最后一维取前一半")
print()
print("  x[..., h:]")
print("     ...   -> 同上")
print("     h:    -> 最后一维取后一半")
print()
q = torch.arange(2 * 4 * 6 * 8).reshape(2, 4, 6, 8).float()
print(f"  q.shape = {tuple(q.shape)}   n = 4")
print(f"  q[..., :4]  -> {tuple(q[..., :4].shape)}   ... 补了 3 个冒号(前 3 维保留)")
print(f"  q[..., 4:]  -> {tuple(q[..., 4:].shape)}   同上")
print()
print("  等价展开:")
print(f"    q[..., :4]  ==  q[:, :, :, :4]  ? {torch.equal(q[..., :4], q[:, :, :, :4])}")

print("\n" + "=" * 78)
print("最后一遍总结(两句话)")
print("=" * 78)
print("  :      = '这一维我全要'(保留)")
print("  ...    = (n - k) 个 : 的简写, 也就是说'接下来 n-k 个维度我全要'")
