[project]
name = "learn-minimind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DevilDouble12312", email = "DevilDouble12312@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "torch>=2.9.0",
    "transformers>=4.57.1,<5",
]
[project.scripts]
learn-minimind = "learn_minimind:main"


[tool.uv.sources]
torch = { index = "pytorch-cu126" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true          # 只允许被 tool.uv.sources 显式引用的包使用，不参与默认解析

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
